# Generated by Django 4.2.4 on 2023-09-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name='نام دسته بندی')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_name', models.CharField(max_length=199, verbose_name='نام تحویل گیرنده')),
                ('reciver_adress', models.TextField(verbose_name='آدرس تحویل گیرنده')),
                ('reciver_phone', models.CharField(max_length=11, verbose_name='شماره تحویل گیرنده')),
                ('order_full_price', models.PositiveBigIntegerField(verbose_name='قیمت کل سفارش')),
                ('order_date', models.DateField(auto_now=True, verbose_name='تاریخ سفارش')),
                ('order_delivery_date', models.DateTimeField(verbose_name='تاریخ تحویل سفارش')),
                ('status', models.CharField(choices=[('4', 'در حال ارسال'), ('6', 'انصراف داده شد'), ('1', 'سبد خرید'), ('5', 'تحویل شد'), ('3', 'درانتظار تایید'), ('2', 'در انتظار پرداخت')], max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99, verbose_name=' نام محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس محصول')),
                ('description', models.TextField(verbose_name='  توضیحات محصول')),
                ('stock', models.PositiveIntegerField(verbose_name='موجودی محصول')),
                ('price', models.PositiveBigIntegerField()),
                ('discout', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تخفیف محصول')),
                ('special', models.BooleanField(verbose_name='ویژه')),
                ('selled_count', models.IntegerField(verbose_name='تعداد فروش')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
            },
        ),
    ]
