# Generated by Django 4.2.4 on 2023-09-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('3', 'درانتظار تایید'), ('1', 'سبد خرید'), ('6', 'انصراف داده شد'), ('4', 'در حال ارسال'), ('2', 'در انتظار پرداخت'), ('5', 'تحویل شد')], max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='  توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selled_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی محصول'),
        ),
    ]
